# Generated by Django 5.1.6 on 2025-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
