# Generated by Django 5.1.6 on 2025-03-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_alter_students_date_of_birth_alter_students_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
