# Generated by Django 5.1.6 on 2025-03-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_rename_firstname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
