# Generated by Django 5.1.6 on 2025-03-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_rename_first_name_students_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
